import profile from "../asset/profile.jpg"
export const image = profile
export const productData=[
    {
      id: 97865435671,
      product_name: "Nike Air Force1",
      product_price: 99.43,
      product_image: profile,
      product_status:"Availaible",  
      imageURL: profile,
      description: " One of the best sneaker in world that helps you walk miles comfortably ",
      category: "CLOTHES & FOOTWEAR",
      brand: "Nike",
      product_type: "New",
      product_size: 343.32,
      product_color: ["green", "red", "White", "black"],
      product_weight: 12,
      product_quantity: 5,   
      product_model_number:  "0942022me32",
      product_serial_number:"M93468V3983232"
    },
    {
      id: 7564523452,
      product_name: "Nike Air Force1",
      product_price: 99.43,
      product_image: profile,
      product_status:"Availaible",  
      imageURL: profile,
      description: " One of the best sneaker in world that helps you walk miles comfortably ",
      category: "CLOTHES & FOOTWEAR",
      brand: "Nike",
      product_type: "New",
      product_size: 343.32,
      product_color: ["green", "red", "White", "black"],
      product_weight: 12,
      product_quantity: 5,   
      product_model_number:  "0942022me32",
      product_serial_number:"M93468V3983232"
    },
    {
      id: 5345673,
      product_name: "Nike Air Force1",
      product_price: 99.43,
      product_image: profile,
      product_status:"Availaible",  
      imageURL: profile,
      description: " One of the best sneaker in world that helps you walk miles comfortably ",
      category: "CLOTHES & FOOTWEAR",
      brand: "Nike",
      product_type: "New",
      product_size: 343.32,
      product_color: ["green", "red", "White", "black"],
      product_weight: 12,
      product_quantity: 5,   
      product_model_number:  "0942022me32",
      product_serial_number:"M93468V3983232"
    },
    {
      id: 2345664,
      product_name: "Nike Air Force1",
      product_price: 99.43,
      product_image: profile,
      product_status:"Availaible",  
      imageURL: profile,
      description: " One of the best sneaker in world that helps you walk miles comfortably ",
      category: "CLOTHES & FOOTWEAR",
      brand: "Nike",
      product_type: "New",
      product_size: 343.32,
      product_color: ["green", "red", "White", "black"],
      product_weight: 12,
      product_quantity: 5,   
      product_model_number:  "0942022me32",
      product_serial_number:"M93468V3983232"
    },
    {
      id: 432235,
      product_name: "Nike Air Force1",
      product_price: 99.43,
      product_image: profile,
      product_status:"Availaible",  
      imageURL: profile,
      description: " One of the best sneaker in world that helps you walk miles comfortably ",
      category: "CLOTHES & FOOTWEAR",
      brand: "Nike",
      product_type: "New",
      product_size: 343.32,
      product_color: ["green", "red", "White", "black"],
      product_weight: 12,
      product_quantity: 5,   
      product_model_number:  "0942022me32",
      product_serial_number:"M93468V3983232"
    },
   

]